### ISSUE TITLE
Errors in library for chart type "Euler"

### ISSUE THREAD

**Issue by KrautGTI** [upsetjs/chartjs-chart-venn#37]
When I run the euler.html code inside of the samples folder in this repo, the euler chart does not load and has this error: 
```
"venn.esm.js:344 Uncaught TypeError: Cannot read properties of undefined (reading 'bisect')
    at distanceFromIntersectArea (venn.esm.js:344:10)
    at greedyLayout (venn.esm.js:683:18)
    at bestInitialLayout (venn.esm.js:503:17)
    at venn (venn.esm.js:287:19)
    at layout (venn.esm.js:1818:18)
    at euler (euler.ts:55:13)
    at EulerDiagramController.computeLayout (EulerDiagramController.ts:16:12)
    at EulerDiagramController.updateElements (VennDiagramController.ts:85:20)
    at EulerDiagramController.update (VennDiagramController.ts:70:10)
    at EulerDiagramController._update (chart.js@~4.1.1:19:54665)"
```
**To Reproduce**

Try running chartjs-chart-venn-main/samples/euler.html and check the console.

**Expected behavior**

Loads a euler diagram :)

**Context**

- Browser: Chrome @latest

**Comment by KrautGTI** [comment]
Thank you!
